import { Types } from "mongoose"

export default interface myResponse{
    status: Boolean,
    msg?: string | Types.ObjectId|string[],
    version?: string | {},
    uId?: string,
    count?: number,
    notifications?: {},
    policies?: {},
    groups?: {},
    procedures?: {},
    controls?: {},
    control?: {},
    versions?: {},
    procedure?: {},
    policy?: {},
    comment?: string | {},
    templates?: {},
    projects?: {},
    project?: {},
    users?: {},
    user?: {},
    scope?: string | {},
    scopes?: {},
    role?: {},
    roles?: {},
    risk?: {},
    tag?: {},
    data?: any,
    accessToken?:string,
    refToken?:string,
    contentType?:string,
    filename?:string,
    email?:string,
    mfa?:boolean,
    _errorCode?:number,
    req3rdPartyMFA?:boolean
}